title: Bern AI in RadioTherapy Symposium (BART)
preposition: ""
description: >-
  BART, at the University of Bern, March 14th 2025.
baseurl: "/bart25" # the subpath of your site, e.g. /blog
url: "https://ubern-mia.github.io/bart25" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  navigation:
    logo:
      name: about ARTORG
      #img: "/assets/images/artorg-logo-transparent.png"
      url: "https://www.artorg.unibe.ch/"
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Abstract Submission
        relative_url: /submission/
      - name: Location
        relative_url: /location/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to reach us
        relative_url: /location/

  link_preview:
    disable: false

  # Live indications
  live:
    date: 14.03.2025
    timezone: GMT+1
    stop: 480 # in minutes
    streaming:
      enable: true
      pause: 60 # in minutes
      prepend: 5 # in minutes
      extend: 5 # in minutes
    demo:
      enable: false
      duration: 300 # in seconds
      pause: 10 # in seconds

  map:
    # Initial map center point
    home_coord: 46.9480, 7.4474
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Information
        color: info
      - name: Keynotes
        color: warning
      - name: Industry
        color: secondary
      - name: Panel
        color: success

  speakers:
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: "/location"
    # Main page title shown on location/room navigation bar
    navbar_title: "Location"
    # Show map on location main page
    map: False

  program:
    url: "/program"
    time_steps: 10
    show_alltimes: true
